### ISSUE TITLE
bug: SegFault

### ISSUE THREAD

**Issue by QLutz** [bentoml/OpenLLM#299]
### Describe the bug

Trying to run a LLaMa 13B model, I encounter a Segmentation Fault error

### To reproduce

Installed OpenLLM by running
```bash
pip install "openllm[llama, vllm, fine-tune]"
pip install scipy
```
Started model with
```bash
openllm start llama --model-id huggyllama/llama-13b --debug
```

### Logs

```shell
Segmentation fault
```

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.5
`python`: 3.9.2
`platform`: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
`uid_gid`: 0:0
<details><summary><code>pip_packages</code></summary>

<br>

```
accelerate==0.22.0
aiohttp==3.8.5
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
bentoml==1.1.5
bitsandbytes==0.41.1
build==1.0.0
cattrs==23.1.2
certifi==2020.6.20
chardet==4.0.0
charset-normalizer==3.2.0
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==2.2.1
cmake==3.27.2
coloredlogs==15.0.1
contextlib2==21.6.0
cuda-python==12.2.0
Cython==3.0.2
datasets==2.14.4
dbus-python==1.2.16
deepmerge==1.1.0
Deprecated==1.2.14
dill==0.3.7
distro-info==1.0
exceptiongroup==1.1.3
fairscale==0.4.13
fastapi==0.103.1
fastcore==1.5.29
filelock==3.12.3
filetype==1.2.0
frozenlist==1.4.0
fs==2.4.16
fsspec==2023.9.0
ghapi==1.0.4
grpcio==1.57.0
h11==0.14.0
httpcore==0.17.3
httplib2==0.18.1
httpx==0.24.1
huggingface-hub==0.16.4
humanfriendly==10.0
idna==2.10
importlib-metadata==6.0.1
inflection==0.5.1
Jinja2==3.1.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
lit==16.0.6
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.5
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
networkx==3.1
ninja==1.11.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
openllm==0.3.0
openllm-client==0.3.0
openllm-core==0.3.0
opentelemetry-api==1.18.0
opentelemetry-instrumentation==0.39b0
opentelemetry-instrumentation-aiohttp-client==0.39b0
opentelemetry-instrumentation-asgi==0.39b0
opentelemetry-sdk==1.18.0
opentelemetry-semantic-conventions==0.39b0
opentelemetry-util-http==0.39b0
optimum==1.12.0
orjson==3.9.5
packaging==23.1
pandas==2.1.0
pathspec==0.11.2
peft==0.5.0
Pillow==10.0.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
prometheus-client==0.17.1
protobuf==4.24.2
psutil==5.9.5
pyarrow==13.0.0
pycurl==7.43.0.6
pydantic==1.10.12
Pygments==2.16.1
PyGObject==3.38.0
pynvml==11.5.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
PySimpleSOAP==1.16.2
python-apt==2.2.1
python-dateutil==2.8.2
python-debian==0.1.39
python-debianbts==3.1.0
python-json-logger==2.0.7
python-multipart==0.0.6
python-snappy==0.5.3
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
ray==2.6.3
referencing==0.30.2
regex==2023.8.8
reportbug==7.10.3+deb11u1
requests==2.25.1
rich==13.5.2
rpds-py==0.10.2
safetensors==0.3.3
schema==0.7.5
scipy==1.11.2
sentencepiece==0.1.99
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tokenizers==0.13.3
tomli==2.0.1
torch==2.0.1
tornado==6.3.3
tqdm==4.66.1
transformers==4.33.0
triton==2.0.0
trl==0.7.1
typing_extensions==4.7.1
tzdata==2023.3
unattended-upgrades==0.1
urllib3==1.26.5
uvicorn==0.23.2
vllm==0.1.4
watchfiles==0.20.0
wcwidth==0.2.6
wrapt==1.15.0
xformers==0.0.21
xxhash==3.3.0
yarl==1.9.2
zipp==3.16.2
```

</details>

- `transformers` version: 4.33.0
- Platform: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.9.2
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### System information (Optional)

`a2-highgpu-1g` from GCP with 1xA100 80GB

**Comment by aarnphm** [comment]
I have been able to reproduce this and I will release a new patch promptly. Thank you for reporting this! Sorry for any inconvenience

**Comment by aarnphm** [comment]
This should be fixed with 0.3.2

**Comment by jeffzhengye** [comment]
> This should be fixed with 0.3.2
no, still get Segmentation fault (core dumped)
![image](https://github.com/bentoml/OpenLLM/assets/4641009/b1115910-4005-4b4a-a586-c74e6602b2fa)

**Comment by aarnphm** [comment]
you need to do `pip install -U openllm`

chances are `openllm-core` and `openllm-client` are not upgraded.
